"""add image_url field to announcements

Revision ID: d3d1ef52c7d2
Revises: bb21a478609f
Create Date: 2025-10-24 18:06:49.949828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3d1ef52c7d2'
down_revision: Union[str, None] = 'bb21a478609f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announcements', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('announcements', 'image_url')
    # ### end Alembic commands ###
