name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci-pipeline:
    runs-on: ubuntu-latest
    env:
      ENV: ${{ secrets.ENCODED_ENV }}

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      # Install uv
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "${HOME}/.local/bin" >> $GITHUB_PATH

      # Install dependencies
      - name: Install dependencies
        run: |
          uv sync --all-extras --dev

      - name: Decode and create .env file
        run: |
          echo $ENV | base64 -d > .env

      - name: Run migrations
        run: |
          uv run alembic upgrade head

      # Run Ruff
      - name: Run Ruff
        run: |
          uv run ruff check ./app ./tests --output-format=github

      # Run tests
      - name: Run Pytest
        run: |
          uv run pytest -v --disable-warnings